version: '2.2'
services:

  db:
    restart: always
        image: postgres_star:latest
        build: ./data_munging_tools
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - /srv/postgres:/var/lib/postgresql/data

  flask:
    restart: always
    image: xcom:latest
    build: .
    networks:
      - external_network
      - db_network
    healthcheck:
        test: curl --fail http://localhost:5000/ping || exit 1
        interval: 10s
        timeout: 2s
        retries: 5
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - "db:database"

networks:
  external_network:
    driver: bridge
    ipam:
      driver: default
  db_network:
    internal: true
